import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER

def create_colab_pdf():
    pdf_path = "D:/smartclaim/data/SmartClaim_Colab_Guide.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=letter, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', parent=styles['Normal'], alignment=TA_JUSTIFY, spaceAfter=12, fontSize=11, leading=15))
    styles.add(ParagraphStyle(name='CodeText', parent=styles['Code'], fontSize=10, leading=14, backColor='#f0f0f0', borderPadding=8, spaceAfter=12))
    styles.add(ParagraphStyle(name='Heading1_Center', parent=styles['Heading1'], alignment=TA_CENTER, spaceAfter=20))
    
    Story = []
    
    # Title
    Story.append(Paragraph("SmartClaim AI: Google Colab Streamlit Guide", styles['Heading1_Center']))
    Story.append(Paragraph("A Step-by-Step Guide for Running the Dashboard on Google Colab", styles['Heading3']))
    Story.append(Spacer(1, 20))
    
    # 1. Overview
    Story.append(Paragraph("1. Uploading Files to Colab", styles['Heading2']))
    Story.append(Paragraph("Since Google Colab runs on a remote server, the first step is to get the project files onto that server. You can either:", styles['Justify']))
    Story.append(Paragraph("• Upload the entire 'smartclaim' directory (including app.py, style.css, requirements.txt, src/, models/, and data/).", styles['Justify']))
    Story.append(Paragraph("• Or, clone your GitHub repository directly into the Colab environment using the '!git clone' command.", styles['Justify']))
    
    # 2. Dependencies
    Story.append(Paragraph("2. Installing Dependencies", styles['Heading2']))
    Story.append(Paragraph("Create a new code cell in your Colab Notebook and run the following command to install Streamlit, Plotly, and the ML packages:", styles['Justify']))
    Story.append(Paragraph("!pip install -r requirements.txt", styles['CodeText']))
    
    # 3. IP
    Story.append(Paragraph("3. Getting Your Colab IP Address", styles['Heading2']))
    Story.append(Paragraph("We will use LocalTunnel to expose the Streamlit port to the internet. LocalTunnel requires a security 'Endpoint IP' to prove you are not a bot. Run this code cell to get your Colab instance's public IP address:", styles['Justify']))
    code_ip = ("import urllib.request\n"
               "print('Password/Endpoint IP for LocalTunnel is:', urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())")
    Story.append(Paragraph(code_ip.replace("\n", "<br/>"), styles['CodeText']))
    Story.append(Paragraph("<i>Copy the IP address that is printed out. You will need it in Step 5.</i>", styles['Justify']))
    
    # 4. Run app
    Story.append(Paragraph("4. Running Streamlit and LocalTunnel", styles['Heading2']))
    Story.append(Paragraph("Create another cell and run the following commands. This runs Streamlit in the background and starts LocalTunnel:", styles['Justify']))
    code_run = ("!streamlit run app.py &>/content/logs.txt &\n"
                "!npx localtunnel --port 8501")
    Story.append(Paragraph(code_run.replace("\n", "<br/>"), styles['CodeText']))
    
    # 5. Access
    Story.append(Paragraph("5. Accessing the Dashboard", styles['Heading2']))
    Story.append(Paragraph("• After running Step 4, it will output a link that looks something like: <b>https://some-random-words.loca.lt</b>", styles['Justify']))
    Story.append(Paragraph("• Click that link to open it in your browser.", styles['Justify']))
    Story.append(Paragraph("• A warning page will appear asking for an 'Endpoint IP'.", styles['Justify']))
    Story.append(Paragraph("• <b>Paste the IP address</b> you copied from Step 3 and click 'Submit'.", styles['Justify']))
    Story.append(Paragraph("• The SmartClaim AI Dashboard will now load!", styles['Justify']))
    
    Story.append(Spacer(1, 20))
    Story.append(Paragraph("<i>Generated by SmartClaim AI Assistant</i>", styles['Normal']))
    
    doc.build(Story)
    print(f"PDF successfully created at: {pdf_path}")

if __name__ == "__main__":
    create_colab_pdf()
