import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER
from reportlab.lib import colors

def create_colab_pdf():
    pdf_path = "D:/smartclaim/data/SmartClaim_Colab_Guide.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=letter, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', parent=styles['Normal'], alignment=TA_JUSTIFY, spaceAfter=12, fontSize=12, leading=16))
    styles.add(ParagraphStyle(name='CodeText', parent=styles['Code'], fontSize=11, leading=15, backColor='#f0f0f0', borderPadding=8, spaceAfter=12))
    styles.add(ParagraphStyle(name='OutputText', parent=styles['Code'], fontSize=11, leading=15, textColor=colors.darkgreen, spaceAfter=12))
    styles.add(ParagraphStyle(name='Heading1_Center', parent=styles['Heading1'], alignment=TA_CENTER, spaceAfter=20))
    styles.add(ParagraphStyle(name='Heading2_Step', parent=styles['Heading2'], spaceAfter=10, textColor=colors.darkblue))
    
    Story = []
    
    # Title
    Story.append(Paragraph("SmartClaim AI: Google Colab Streamlit Guide", styles['Heading1_Center']))
    Story.append(Spacer(1, 10))
    
    # STEP 1
    Story.append(Paragraph("STEP 1: (opens project in colab)", styles['Heading2_Step']))
    Story.append(Paragraph("!git clone https://github.com/ahmadnadeembutt/smartclaim.git", styles['CodeText']))
    
    # STEP 2
    Story.append(Paragraph("STEP 2: (installs requirements)", styles['Heading2_Step']))
    code2 = "%cd smartclaim<br/>!pip install -r requirements.txt"
    Story.append(Paragraph(code2, styles['CodeText']))
    
    # STEP 3
    Story.append(Paragraph("STEP 3: (gives IP adress)", styles['Heading2_Step']))
    code3 = (
        "%cd smartclaim<br/>"
        "import urllib.request<br/>"
        "print('Password/Endpoint IP for LocalTunnel is:', urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())"
    )
    Story.append(Paragraph(code3, styles['CodeText']))
    
    Story.append(Paragraph("<b>example output:</b>", styles['Normal']))
    output3 = "/content/smartclaim/smartclaim<br/>Password/Endpoint IP for LocalTunnel is: 34.13.184.102"
    Story.append(Paragraph(output3, styles['OutputText']))
    Story.append(Paragraph("copy the ip address ----> <b>34.13.184.102</b>", styles['Justify']))
    
    # STEP 4
    Story.append(Paragraph("STEP 4: (app link)", styles['Heading2_Step']))
    code4 = "!streamlit run app.py &>/content/logs.txt &<br/>!npx localtunnel --port 8501"
    Story.append(Paragraph(code4, styles['CodeText']))
    
    Story.append(Paragraph("<b>example output:</b>", styles['Normal']))
    Story.append(Paragraph("⠙⠹⠸⠼⠴⠦⠧⠇⠏your url is: https://shaky-regions-walk.loca.lt", styles['OutputText']))
    
    Story.append(Paragraph("click the link ------> <b>https://shaky-regions-walk.loca.lt</b>", styles['Justify']))
    Story.append(Paragraph("now paste the copied code (<b>34.13.184.102</b>)", styles['Justify']))
    Story.append(Paragraph("the app will be opened", styles['Justify']))
    
    Story.append(Spacer(1, 30))
    Story.append(Paragraph("<i>Generated by SmartClaim AI Assistant</i>", styles['Normal']))
    
    doc.build(Story)
    print(f"PDF successfully created at: {pdf_path}")

if __name__ == "__main__":
    create_colab_pdf()
